## YAML Template.
services:  
    iaato_user.profile.form.type:
        class: Ensiie\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: iaato_user_profile }
