<?php

namespace Ensiie\IaatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningRepository extends EntityRepository
{
    public function trieDate()
    {
        return $this->createQueryBuilder('p')
                    ->add('orderBy','p.day DESC')
                    ->getQuery()
                    ->getResult();
    }
    public function trieShip()
    {
        return $this->_em
                     ->createQuery('SELECT p FROM EnsiieIaatoBundle:Ship s, EnsiieIaatoBundle:Planning p
                     WHERE s.id = p.ship ORDER BY s.name ASC') 
                    ->getResult();
    }
    public function trieCompany()
    {
        return $this->_em
                    ->createQuery('SELECT p FROM EnsiieIaatoBundle:Ship s, EnsiieIaatoBundle:Planning p, EnsiieIaatoBundle:Company c 
                      WHERE s.id = p.ship AND s.company = c.id ORDER BY c.name ASC') 
                    ->getResult();
    }
    public function trieMe($user)
    {   
       $query= $this->_em
                    ->createQuery('SELECT p FROM EnsiieUserBundle:User u, EnsiieIaatoBundle:Planning p 
                     WHERE u.ship = p.ship AND u.ship = :id ORDER BY p.day DESC'); 
        $query->setParameter('id',$user->getShip());
        return $query->getResult();
       
    }

}
