iaato_planning:
    pattern: /planning/{sort}
    defaults: {_controller: EnsiieIaatoBundle:Iaato:planning, sort:date}
    requirements:
        sort: date|ship|company

iaato_homepage:
    pattern: /
    defaults: {_controller: EnsiieIaatoBundle:Iaato:index }
