iaato_planning:
    pattern: /planning/{sort}
    defaults: {_controller: EnsiieIaatoBundle:Iaato:planning, sort:date}
    requirements:
        sort: date|ship|company|me

iaato_homepage:
    pattern: /
    defaults: {_controller: EnsiieIaatoBundle:Iaato:index }

iaato_admin:
    pattern: /admin
    defaults: {_controller: EnsiieIaatoBundle:Iaato:admin }
