parameters:
#    ensiie_iaato.example.class: Ensiie\IaatoBundle\Example

services:
#    ensiie_iaato.example:
#        class: %ensiie_iaato.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
